const LLVMtype = @import("types.zig");

pub extern fn LLVMCreateBinary(MemBuf: LLVMtype.LLVMMemoryBufferRef, Context: LLVMtype.LLVMContextRef, ErrorMessage: [*c][*c]u8) LLVMtype.LLVMBinaryRef;
pub extern fn LLVMDisposeBinary(BR: LLVMtype.LLVMBinaryRef) void;
pub extern fn LLVMBinaryCopyMemoryBuffer(BR: LLVMtype.LLVMBinaryRef) LLVMtype.LLVMMemoryBufferRef;
pub extern fn LLVMBinaryGetType(BR: LLVMtype.LLVMBinaryRef) LLVMtype.LLVMBinaryType;
pub extern fn LLVMMachOUniversalBinaryCopyObjectForArch(BR: LLVMtype.LLVMBinaryRef, Arch: [*c]const u8, ArchLen: usize, ErrorMessage: [*c][*c]u8) LLVMtype.LLVMBinaryRef;
pub extern fn LLVMObjectFileCopySectionIterator(BR: LLVMtype.LLVMBinaryRef) LLVMtype.LLVMSectionIteratorRef;
pub extern fn LLVMObjectFileIsSectionIteratorAtEnd(BR: LLVMtype.LLVMBinaryRef, SI: LLVMtype.LLVMSectionIteratorRef) LLVMtype.LLVMBool;
pub extern fn LLVMObjectFileCopySymbolIterator(BR: LLVMtype.LLVMBinaryRef) LLVMtype.LLVMSymbolIteratorRef;
pub extern fn LLVMObjectFileIsSymbolIteratorAtEnd(BR: LLVMtype.LLVMBinaryRef, SI: LLVMtype.LLVMSymbolIteratorRef) LLVMtype.LLVMBool;
pub extern fn LLVMDisposeSectionIterator(SI: LLVMtype.LLVMSectionIteratorRef) void;
pub extern fn LLVMMoveToNextSection(SI: LLVMtype.LLVMSectionIteratorRef) void;
pub extern fn LLVMMoveToContainingSection(Sect: LLVMtype.LLVMSectionIteratorRef, Sym: LLVMtype.LLVMSymbolIteratorRef) void;
pub extern fn LLVMDisposeSymbolIterator(SI: LLVMtype.LLVMSymbolIteratorRef) void;
pub extern fn LLVMMoveToNextSymbol(SI: LLVMtype.LLVMSymbolIteratorRef) void;
pub extern fn LLVMGetSectionName(SI: LLVMtype.LLVMSectionIteratorRef) [*c]const u8;
pub extern fn LLVMGetSectionSize(SI: LLVMtype.LLVMSectionIteratorRef) u64;
pub extern fn LLVMGetSectionContents(SI: LLVMtype.LLVMSectionIteratorRef) [*c]const u8;
pub extern fn LLVMGetSectionAddress(SI: LLVMtype.LLVMSectionIteratorRef) u64;
pub extern fn LLVMGetSectionContainsSymbol(SI: LLVMtype.LLVMSectionIteratorRef, Sym: LLVMtype.LLVMSymbolIteratorRef) LLVMtype.LLVMBool;
pub extern fn LLVMGetRelocations(Section: LLVMtype.LLVMSectionIteratorRef) LLVMtype.LLVMRelocationIteratorRef;
pub extern fn LLVMDisposeRelocationIterator(RI: LLVMtype.LLVMRelocationIteratorRef) void;
pub extern fn LLVMIsRelocationIteratorAtEnd(Section: LLVMtype.LLVMSectionIteratorRef, RI: LLVMtype.LLVMRelocationIteratorRef) LLVMtype.LLVMBool;
pub extern fn LLVMMoveToNextRelocation(RI: LLVMtype.LLVMRelocationIteratorRef) void;
pub extern fn LLVMGetSymbolName(SI: LLVMtype.LLVMSymbolIteratorRef) [*c]const u8;
pub extern fn LLVMGetSymbolAddress(SI: LLVMtype.LLVMSymbolIteratorRef) u64;
pub extern fn LLVMGetSymbolSize(SI: LLVMtype.LLVMSymbolIteratorRef) u64;
pub extern fn LLVMGetRelocationOffset(RI: LLVMtype.LLVMRelocationIteratorRef) u64;
pub extern fn LLVMGetRelocationSymbol(RI: LLVMtype.LLVMRelocationIteratorRef) LLVMtype.LLVMSymbolIteratorRef;
pub extern fn LLVMGetRelocationType(RI: LLVMtype.LLVMRelocationIteratorRef) u64;
pub extern fn LLVMGetRelocationTypeName(RI: LLVMtype.LLVMRelocationIteratorRef) [*c]const u8;
pub extern fn LLVMGetRelocationValueString(RI: LLVMtype.LLVMRelocationIteratorRef) [*c]const u8;
pub extern fn LLVMCreateObjectFile(MemBuf: LLVMtype.LLVMMemoryBufferRef) LLVMtype.LLVMObjectFileRef;
pub extern fn LLVMDisposeObjectFile(ObjectFile: LLVMtype.LLVMObjectFileRef) void;
pub extern fn LLVMGetSections(ObjectFile: LLVMtype.LLVMObjectFileRef) LLVMtype.LLVMSectionIteratorRef;
pub extern fn LLVMIsSectionIteratorAtEnd(ObjectFile: LLVMtype.LLVMObjectFileRef, SI: LLVMtype.LLVMSectionIteratorRef) LLVMtype.LLVMBool;
pub extern fn LLVMGetSymbols(ObjectFile: LLVMtype.LLVMObjectFileRef) LLVMtype.LLVMSymbolIteratorRef;
pub extern fn LLVMIsSymbolIteratorAtEnd(ObjectFile: LLVMtype.LLVMObjectFileRef, SI: LLVMtype.LLVMSymbolIteratorRef) LLVMtype.LLVMBool;

pub const LLVMBinaryTypeArchive: c_int = 0;
pub const LLVMBinaryTypeMachOUniversalBinary: c_int = 1;
pub const LLVMBinaryTypeCOFFImportFile: c_int = 2;
pub const LLVMBinaryTypeIR: c_int = 3;
pub const LLVMBinaryTypeWinRes: c_int = 4;
pub const LLVMBinaryTypeCOFF: c_int = 5;
pub const LLVMBinaryTypeELF32L: c_int = 6;
pub const LLVMBinaryTypeELF32B: c_int = 7;
pub const LLVMBinaryTypeELF64L: c_int = 8;
pub const LLVMBinaryTypeELF64B: c_int = 9;
pub const LLVMBinaryTypeMachO32L: c_int = 10;
pub const LLVMBinaryTypeMachO32B: c_int = 11;
pub const LLVMBinaryTypeMachO64L: c_int = 12;
pub const LLVMBinaryTypeMachO64B: c_int = 13;
pub const LLVMBinaryTypeWasm: c_int = 14;
pub const LLVMBinaryTypeOffload: c_int = 15;
